[pytest]
log_cli = 1
log_cli_level = INFO
log_cli_format = %(asctime)s [%(filename)s - %(funcName)s : %(lineno)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
asyncio_mode = auto
testpaths = tests
;addopts = -v -s
pythonpath = . tests # 不可以加入src, 可能会导致引入mcp.server的操作，影响了加载的顺序
